operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    dx-excshell-1:
      license: Apache-2.0
      actions:
        aem-gql-demo:
          function: actions/aem/gql-demo/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            IMS_HOST: $IMS_HOST
            METASCOPES: $METASCOPES
            TECH_ACCOUNT_ID: $TECH_ACCOUNT_ID
            ORG_ID: $ORG_ID
            CLIENT_ID: $CLIENT_ID
            CLIENT_SECRET: $CLIENT_SECRET
            PRIVATE_KEY: $PRIVATE_KEY
            AEM_AUTHOR: $AEM_AUTHOR
            AEM_GQL_PATH: $AEM_GQL_PATH
            AEM_GQL_PATH_PROXY: $AEM_GQL_PATH_PROXY
            USE_AEM_PROXY: $USE_AEM_PROXY
        ajo-vf-demo:
          function: actions/ajo/vf-demo/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            AJO_FRAGMENTS_URL: $AJO_FRAGMENTS_URL
            AJO_API_KEY: $AJO_API_KEY
            SANDBOX_NAME: $SANDBOX_NAME
        ajo-preview-template:
          function: actions/ajo/preview-template/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            AJO_MESSAGE_GQL_URL: $AJO_MESSAGE_GQL_URL
            AJO_API_KEY: $AJO_API_KEY
            SANDBOX_NAME: $SANDBOX_NAME
        ajo-render-preview:
          function: actions/ajo/render-preview/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            # optional: where to fetch VF bodies from (if you have an endpoint)
            AJO_FRAGMENTS_URL: $AJO_FRAGMENTS_URL
            AJO_API_KEY: $AJO_API_KEY
            SANDBOX_NAME: $SANDBOX_NAME