operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    dx-excshell-1:
      license: Apache-2.0
      actions:
        aem-gql-demo:
          function: actions/aem/gql-demo/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            IMS_HOST: $IMS_HOST
            METASCOPES: $METASCOPES
            TECH_ACCOUNT_ID: $TECH_ACCOUNT_ID
            ORG_ID: $ORG_ID
            CLIENT_ID: $CLIENT_ID
            CLIENT_SECRET: $CLIENT_SECRET
            PRIVATE_KEY: $PRIVATE_KEY
            AEM_AUTHOR: $AEM_AUTHOR
            AEM_GQL_PATH: $AEM_GQL_PATH
            AEM_GQL_PATH_PROXY: $AEM_GQL_PATH_PROXY
            USE_AEM_PROXY: $USE_AEM_PROXY
        ajo-vf-demo:
          function: actions/ajo/vf-demo/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            AJO_FRAGMENTS_URL: $AJO_FRAGMENTS_URL
            AJO_API_KEY: $AJO_API_KEY
            SANDBOX_NAME: $SANDBOX_NAME
        ajo-template-create:
          function: actions/ajo/template/create/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            AJO_CREATE_TEMPLATE_URL: $AJO_CREATE_TEMPLATE_URL
            AJO_GET_TEMPLATE_URL: $AJO_GET_TEMPLATE_URL
            AJO_BASELINE_TEMPLATE_ID: $AJO_BASELINE_TEMPLATE_ID
            AJO_API_KEY: $AJO_API_KEY
            SANDBOX_NAME: $SANDBOX_NAME
        ajo-template-get:
          function: actions/ajo/template/get/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            AJO_GET_TEMPLATE_URL: $AJO_GET_TEMPLATE_URL
            AJO_API_KEY: $AJO_API_KEY
            SANDBOX_NAME: $SANDBOX_NAME
        ajo-template-update:
          function: actions/ajo/template/update/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            AJO_GET_TEMPLATE_URL: $AJO_GET_TEMPLATE_URL
            AJO_UPDATE_TEMPLATE_URL: $AJO_UPDATE_TEMPLATE_URL
            AJO_API_KEY: $AJO_API_KEY
            SANDBOX_NAME: $SANDBOX_NAME
        ajo-template-render:
          function: actions/ajo/template/render/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            AJO_GET_TEMPLATE_URL: $AJO_GET_TEMPLATE_URL
            AJO_API_KEY: $AJO_API_KEY
            SANDBOX_NAME: $SANDBOX_NAME
        aem-prb-list:
          function: actions/aem/prb-list/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            IMS_HOST: $IMS_HOST
            METASCOPES: $METASCOPES
            TECH_ACCOUNT_ID: $TECH_ACCOUNT_ID
            ORG_ID: $ORG_ID
            CLIENT_ID: $CLIENT_ID
            CLIENT_SECRET: $CLIENT_SECRET
            PRIVATE_KEY: $PRIVATE_KEY
            AEM_AUTHOR: $AEM_AUTHOR
            AEM_GQL_PATH: $AEM_GQL_PATH
            AEM_GQL_PATH_PROXY: $AEM_GQL_PATH_PROXY
            USE_AEM_PROXY: $USE_AEM_PROXY